# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

EDITOR='vim'

# overrides theme set in .zpreztorc
prompt powerlevel10k

# enable or disable custom themes on the fly
CUSTOM_THEMES_ENABLED=0

# load custom themes
if [[ CUSTOM_THEMES_ENABLED -eq 1 && -d $HOME/.zsh_user_themes ]]; then
  # file namings must be: prompt_THEMENAME_setup
  fpath=( $HOME/.zsh_user_themes $fpath )
  autoload -Uz promptinit; promptinit
  # set a custom theme here. This overrides .zpreztorc theme setting.
  prompt sorinEdit
fi

# custom history size
export HISTSIZE=20000
# save history after logout
export SAVEHIST=20000
# history file
export HISTFILE=~/.zsh_history

autoload zmv

# load environment
source $HOME/.zsh_env

# load aliases
source $HOME/.zsh_aliases

# load custom/env specific stuff, but only if file exists
if [[ -a $HOME/.zsh_custom ]]; then
source $HOME/.zsh_custom
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
