#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# aliases
alias nv=nvim
alias l='ls -lhA'
alias lr='ll -RA'
alias lt='ll -t'
#alias jekyll='if [! -d $HOME/.gems_$JEKYLL_VERSION ]; then mkdir $HOME/.gems_$JEKYLL_VERSION; fi ; docker run --rm -v="$PWD:/srv/jekyll" -v="$HOME/.gems_$JEKYLL_VERSION:/srv/gems" --env BUNDLE_PATH=/srv/gems" -it -p 35729:35729 -p 4000:4000 jekyll/jekyll:$JEKYLL_VERSION jekyll'
alias jk='jekyll'
#alias jekyll='docker run --rm -v="$PWD:/srv/jekyll" -v="$HOME/.gems_$JEKYLL_VERSION:/srv/gems" --env "BUNDLE_PATH=/srv/gems" -it -p 35729:35729 -p 4000:4000 jekyll/jekyll:$JEKYLL_VERSION jekyll'
alias gdb='nocorrect gdb'
alias jkk='$HOME/dotfiles/bin/check_jk_running.sh'
alias tat='tmux a -t'
alias ebook-convert='$HOME/calibre-bin/calibre/ebook-convert'
alias ydl='youtube-dl'

autoload zmv

# custom history size
export HISTSIZE=20000
# save history after logout
export SAVEHIST=20000
# history file
export HISTFILE=~/.zsh_history

# exports
export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"

# custom binaries
export PATH="$PATH:$HOME/.bin"
export PATH="$PATH:$HOME/.bin2"

# golang
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$(go env GOPATH)/bin
export GOPATH=$(go env GOPATH)

# swift
export PATH=/opt/swift/usr/bin:$PATH

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

