code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension DotJoshJohnson.xml
code --install-extension EditorConfig.EditorConfig
code --install-extension IBM.XMLLanguageSupport
code --install-extension SonarSource.sonarlint-vscode
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension Zignd.html-css-class-completion
code --install-extension agauniyal.vscode-caniuse
code --install-extension alefragnani.Bookmarks
code --install-extension bmuskalla.vscode-tldr
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension formulahendry.auto-close-tag
code --install-extension hangxingliu.vscode-nginx-conf-hint
code --install-extension infinity1207.angular2-switcher
code --install-extension johnpapa.read-time
code --install-extension johnstoncode.svn-scm
code --install-extension marquesmps.dockerfile-validator
code --install-extension ms-azuretools.vscode-azurestorage
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-vscode.azure-account
code --install-extension naumovs.color-highlight
code --install-extension octref.vetur
code --install-extension redhat.java
code --install-extension redhat.vscode-xml
code --install-extension robinbentley.sass-indented
code --install-extension schroeter.prettier-vscode-space-parenthesis
code --install-extension vscode-icons-team.vscode-icons
code --install-extension will-stone.plastic
code --install-extension wmaurer.change-case
