code --install-extension 42Crunch.vscode-openapi
code --install-extension AdrianSanguineti.json-parse-validator
code --install-extension alefragnani.Bookmarks
code --install-extension amazonwebservices.aws-toolkit-vscode
code --install-extension anseki.vscode-color
code --install-extension bmuskalla.vscode-tldr
code --install-extension chris-noring.node-snippets
code --install-extension christian-kohler.npm-intellisense
code --install-extension chrmarti.ssh
code --install-extension cschleiden.vscode-github-actions
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension dcortes92.FreeMarker
code --install-extension deerawan.vscode-dash
code --install-extension devadvice.serverlessconsole
code --install-extension DotJoshJohnson.xml
code --install-extension dunstontc.viml
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension firefox-devtools.vscode-firefox-debug
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.code-runner
code --install-extension gerane.Theme-FlatlandDark
code --install-extension gerane.Theme-FlatlandMonokai
code --install-extension GitHub.remotehub
code --install-extension golang.go
code --install-extension GrapeCity.gc-excelviewer
code --install-extension hangxingliu.vscode-nginx-conf-hint
code --install-extension jonsmithers.open-in-vim
code --install-extension loganarnett.lambda-snippets
code --install-extension mads-hartmann.bash-ide-vscode
code --install-extension malmaud.tmux
code --install-extension mark-tucker.aws-cli-configure
code --install-extension mikestead.dotenv
code --install-extension mrmlnc.vscode-duplicate
code --install-extension ms-azure-devops.azure-pipelines
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-audio
code --install-extension ms-vsliveshare.vsliveshare-pack
code --install-extension nick-rudenko.back-n-forth
code --install-extension octref.vetur
code --install-extension piotrpalarz.vscode-gitignore-generator
code --install-extension Pivotal.vscode-spring-boot
code --install-extension prograhammer.tslint-vue
code --install-extension redhat.java
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension rogalmic.bash-debug
code --install-extension rust-lang.rust
code --install-extension SonarSource.sonarlint-vscode
code --install-extension takkaO.open-window-tab-context
code --install-extension thundra.thundra-debugger
code --install-extension Tyriar.windows-terminal
code --install-extension uyiosa-enabulele.reopenclosedtab
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscjava.vscode-spring-boot-dashboard
code --install-extension vscjava.vscode-spring-initializr
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vsls-contrib.gistfs
code --install-extension will-stone.plastic
code --install-extension Xherdi.fluent-terminal
code --install-extension xshrim.txt-syntax
code --install-extension Zignd.html-css-class-completion
