code --install-extension abusaidm.html-snippets
code --install-extension AdrianSanguineti.json-parse-validator
code --install-extension agauniyal.vscode-caniuse
code --install-extension akamud.vscode-caniuse
code --install-extension alefragnani.Bookmarks
code --install-extension amazonwebservices.aws-toolkit-vscode
code --install-extension anseki.vscode-color
code --install-extension Arjun.swagger-viewer
code --install-extension astallinger.sourcetrail
code --install-extension bmuskalla.vscode-tldr
code --install-extension ccimage.jsonviewer
code --install-extension codezombiech.gitignore
code --install-extension danwahlin.angular2-snippets
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension dcortes92.FreeMarker
code --install-extension deerawan.vscode-dash
code --install-extension devadvice.serverlessconsole
code --install-extension DotJoshJohnson.xml
code --install-extension dunstontc.viml
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.code-runner
code --install-extension gerane.Theme-FlatlandDark
code --install-extension gerane.Theme-FlatlandMonokai
code --install-extension golang.go
code --install-extension GrapeCity.gc-excelviewer
code --install-extension hangxingliu.vscode-nginx-conf-hint
code --install-extension jonsmithers.open-in-vim
code --install-extension loganarnett.lambda-snippets
code --install-extension malmaud.tmux
code --install-extension mark-tucker.aws-cli-configure
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode.sublime-keybindings
code --install-extension octref.vetur
code --install-extension Pivotal.vscode-spring-boot
code --install-extension redhat.java
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension SonarSource.sonarlint-vscode
code --install-extension TabNine.tabnine-vscode
code --install-extension thekalinga.bootstrap4-vscode
code --install-extension thundra.thundra-debugger
code --install-extension Tyriar.terminal-tabs
code --install-extension uyiosa-enabulele.reopenclosedtab
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscjava.vscode-spring-initializr
code --install-extension vscode-icons-team.vscode-icons
code --install-extension will-stone.plastic
code --install-extension xshrim.txt-syntax
code --install-extension Zignd.html-css-class-completion
