code --install-extension SonarSource.sonarlint-vscode
code --install-extension agauniyal.vscode-caniuse
code --install-extension alefragnani.Bookmarks
code --install-extension eamodio.gitlens
code --install-extension eg2.tslint
code --install-extension formulahendry.auto-close-tag
code --install-extension hangxingliu.vscode-nginx-conf-hint
code --install-extension infinity1207.angular2-switcher
code --install-extension johnpapa.read-time
code --install-extension johnstoncode.svn-scm
code --install-extension marquesmps.dockerfile-validator
code --install-extension ms-python.python
code --install-extension naumovs.color-highlight
code --install-extension redhat.java
code --install-extension robinbentley.sass-indented
code --install-extension schroeter.prettier-vscode-space-parenthesis
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wmaurer.change-case
