code --install-extension EditorConfig.EditorConfig
code --install-extension Zignd.html-css-class-completion
code --install-extension abusaidm.html-snippets
code --install-extension alefragnani.Bookmarks
code --install-extension codezombiech.gitignore
code --install-extension danwahlin.angular2-snippets
code --install-extension deerawan.vscode-dash
code --install-extension donjayamanne.githistory
code --install-extension DotJoshJohnson.xml
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.code-runner
code --install-extension gerane.Theme-FlatlandDark
code --install-extension gerane.Theme-FlatlandMonokai
code --install-extension GrapeCity.gc-excelviewer
code --install-extension hangxingliu.vscode-nginx-conf-hint
code --install-extension johnpapa.Angular1
code --install-extension johnpapa.Angular2
code --install-extension ms-python.python
code --install-extension ms-vscode.sublime-keybindings
code --install-extension PeterJausovec.vscode-docker
code --install-extension robertohuertasm.vscode-icons
code --install-extension robinbentley.sass-indented
code --install-extension SonarSource.sonarlint-vscode
code --install-extension thekalinga.bootstrap4-vscode
code --install-extension vscodevim.vim
code --install-extension agauniyal.vscode-caniuse
code --install-extension Angular.ng-template
code --install-extension eamodio.gitlens
code --install-extension eg2.tslint
code --install-extension marquesmps.dockerfile-validator
code --install-extension ms-toolsai.vscode-ai
code --install-extension ms-vscode.azure-account
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension redhat.java
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension wmaurer.change-case
code --install-extension naumovs.color-highlight
