name: 'Linux'

on:
  push:
    branches:
      - main
    paths:
      - setup.sh
      - base/setup_base.sh
      - base/setup_fzf.sh
      - base/setup_zprezto.zsh
      - workspaces/*.sh
      - setups/setup_docker_full.sh
      - setups/setup_env.sh
      - setups/setup_cloud_clients.sh
      - setups/setup_utils.sh
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  testing:
    name: Full setup testing on Ubuntu
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: "script.sh install"
      id: 'scriptsh_install'
      shell: bash
      # 'The Linux and macOS virtual machines both run using passwordless sudo'
      # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
      run: |
        echo "Set BIN2_PATH to $(pwd)/bin2 and DEBIAN_FRONTEND to noninteractive"
        export BIN2_PATH=$(pwd)/bin2
        export DEBIAN_FRONTEND=noninteractive
        bash setup.sh
    - name: "Testing"
      id: 'scriptsh_testing'
      shell: bash
      run: |
        cd tests
        bash packages.sh
        script -e -c 'zsh -i -c ./workspaces.sh'
        script -e -c 'zsh -i -c ./utils.sh'
        script -e -c 'zsh -i -c ./cloud_clients.sh'
  sendNotification:
    name: Send Notification
    runs-on: ubuntu-20.04
    if: ${{ always() }}
    needs: [testing]
    steps:
    - name: Send Push Notification
      uses: fjogeleit/http-request-action@master
      if: always()
      with:
        url: ${{ secrets.NOTIFICATION_WEBHOOK_URI }}
        method: 'POST'
        data: '{ "value1": "[GitHub] ${{ github.repository }}", "value2": "Workflow &quot;${{ github.workflow }}&quot; on branch ${{ github.ref }} finished with status ${{ needs.testing.result }}.", "value3": "<br>Triggered by &quot;${{ github.event_name }}&quot;.<br>Action run on ${{ runner.os }} by ${{ runner.name }}.<br>Commit ${{ github.sha }} on ${{ github.ref }}.<br>https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" }'
